image: ghcr.io/cirruslabs/flutter:stable

pipelines:
  default:
    - step:
        name: "Flutter lint"
        script:
          - flutter doctor -v
          - flutter analyze
    - step:
        name: "Build test (linux)"
        script:
          - apt update
          - yes | apt install clang
          - yes | apt install cmake
          - yes | apt install ninja-build
          - yes | apt install pkg-config
          - yes | apt install libgtk-3-dev
          - flutter build linux